name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number for manual release'
        required: true
        default: '1.0.0'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
        
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build Electron app for Windows
        if: matrix.os == 'windows-latest'
        run: |
          npm run build:win
          
      - name: Build Electron app for macOS
        if: matrix.os == 'macos-latest'
        run: |
          npm run build:mac
          
      - name: Upload Windows artifacts
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v3
        with:
          name: windows-artifacts
          path: |
            dist/*.exe
            dist/*.msi
            dist/latest.yml
            
      - name: Upload macOS artifacts
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v3
        with:
          name: macos-artifacts
          path: |
            dist/*.dmg
            dist/*.zip
            dist/latest-mac.yml

  release:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v3
        
      - name: Display structure of downloaded files
        run: ls -R
        
      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          name: ServMcp ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: |
            windows-artifacts/*.exe
            windows-artifacts/*.msi
            windows-artifacts/latest.yml
            macos-artifacts/*.dmg
            macos-artifacts/*.zip
            macos-artifacts/latest-mac.yml
          body: |
            # ServMcp ${{ github.ref_name }}
            
            ## Installation
            
            ### Windows
            Download and run the exe installer.
            
            ### macOS
            Download and open the dmg file, then drag the app to your Applications folder.
            
            ## Changes in this version
            
            - Initial release